name: 🐛 Bug Report
description: Report a bug in the MISP DDoS Automation project
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide detailed information to help us reproduce and fix the issue.
        
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: Describe what happened...
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Upload file '...'
        3. See error
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: Describe what you expected to happen...
    validations:
      required: true
      
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Relevant error messages or logs
      placeholder: Paste any error messages or log output here...
      render: shell
    validations:
      required: false
      
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low - Minor issue, workaround available
        - Medium - Affects functionality but not critical
        - High - Major functionality broken
        - Critical - System unusable or security issue
      default: 1
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - CLI Tool
        - MISP Client
        - File Parsing (CSV/JSON)
        - Interactive Mode
        - Security Features
        - Setup/Installation
        - Documentation
      default: 0
    validations:
      required: true
      
  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you using?
      placeholder: e.g., v1.0.0 or commit hash
    validations:
      required: false
      
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your system environment
      placeholder: |
        - OS: Windows 11 / macOS 14 / Ubuntu 22.04
        - Python: 3.11.0
        - MISP Version: 2.4.175
        - Connection: HTTPS/HTTP
    validations:
      required: true
      
  - type: checkboxes
    id: security
    attributes:
      label: Security Impact
      description: Does this bug have security implications?
      options:
        - label: This bug could lead to data exposure
        - label: This bug could allow unauthorized access
        - label: This bug could cause denial of service
        - label: This bug involves credential handling
        - label: No security implications
        
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Screenshots, configuration files, or additional details...
    validations:
      required: false