name: 🚀 Feature Request
description: Suggest a new feature for the MISP DDoS Automation project
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide as much detail as possible.
        
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or limitation you're experiencing...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: Describe your proposed solution...
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: Describe any alternative solutions you've considered...
    validations:
      required: false
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Blocking current work
        - Critical - System unusable without this
      default: 1
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system does this affect?
      options:
        - CLI Tool
        - Web Application
        - MISP Integration
        - Security Features
        - Documentation
        - Testing
        - Infrastructure
      default: 0
    validations:
      required: true
      
  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Considerations
      description: Check all that apply
      options:
        - label: This feature requires MISP API changes
        - label: This feature affects security controls
        - label: This feature requires database changes
        - label: This feature needs new dependencies
        - label: This feature affects existing workflows
        - label: I'm willing to contribute to implementation
        
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information, screenshots, or context
      placeholder: Add any other context, mockups, or examples here...
    validations:
      required: false