name: 🔒 Security Vulnerability
description: Report a security vulnerability (private disclosure)
title: "[SECURITY] "
labels: ["security", "critical"]
assignees: ["PabloPenguin"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **SECURITY NOTICE**: If this is a critical security vulnerability, please email security@yourorganization.com instead of creating a public issue.
        
        For responsible disclosure of security vulnerabilities, we follow industry best practices.
        
  - type: textarea
    id: vulnerability
    attributes:
      label: Vulnerability Description
      description: Describe the security vulnerability
      placeholder: Provide a clear description of the security issue...
    validations:
      required: true
      
  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this vulnerability?
      options:
        - Low - Limited impact
        - Medium - Moderate impact
        - High - Significant impact
        - Critical - Severe impact, immediate action required
      default: 2
    validations:
      required: true
      
  - type: dropdown
    id: category
    attributes:
      label: Vulnerability Category
      description: What type of vulnerability is this?
      options:
        - Injection (SQL, Command, Path)
        - Authentication/Authorization
        - Information Disclosure
        - Cross-Site Scripting (XSS)
        - Denial of Service
        - Cryptographic Issue
        - Input Validation
        - File Upload Security
        - Other
      default: 8
    validations:
      required: true
      
  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: What could an attacker accomplish?
      placeholder: Describe the potential impact if exploited...
    validations:
      required: true
      
  - type: textarea
    id: reproduction
    attributes:
      label: Proof of Concept
      description: Steps to reproduce (if safe to share)
      placeholder: |
        Provide reproduction steps if they don't pose additional risk.
        For critical vulnerabilities, contact us privately first.
    validations:
      required: false
      
  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: How can this be fixed?
      placeholder: Any suggestions for fixing this vulnerability...
    validations:
      required: false
      
  - type: checkboxes
    id: affected
    attributes:
      label: Affected Components
      description: Which components are affected?
      options:
        - label: CLI Tool
        - label: MISP Client
        - label: File Processing
        - label: Authentication
        - label: Web Application (future)
        - label: Documentation/Examples
        
  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      description: Disclosure preferences
      options:
        - label: I agree to responsible disclosure practices
        - label: I would like credit for this discovery
        - label: I prefer to remain anonymous
        - label: I have not shared this publicly elsewhere
        
  - type: textarea
    id: contact
    attributes:
      label: Contact Information
      description: How can we reach you? (optional)
      placeholder: Email or preferred contact method for coordinating disclosure...
    validations:
      required: false