name: Refresh MISP Dashboard Data

on:
  schedule:
    # Run every 30 minutes during business hours (8 AM - 6 PM UTC)
    - cron: '*/30 8-18 * * 1-5'
    # Run every 2 hours outside business hours and weekends  
    - cron: '0 */2 * * *'
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [ main ]
    paths:
      - 'cli/**'
      - '.github/workflows/refresh-misp-data.yml'

permissions:
  contents: write

jobs:
  refresh-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install CLI dependencies
      run: |
        cd cli
        pip install -r requirements.txt
        
    - name: Generate comprehensive sample MISP data
      run: |
        mkdir -p webapp/frontend/public/data
        
        # Create realistic sample MISP data for proof of concept
        cat > webapp/frontend/public/data/dashboard-data.json << 'EOF'
        {
          "events": [
            {
              "id": "1001",
              "info": "DDoS Attack Campaign Against Financial Sector",
              "date": "2025-10-07",
              "threat_level_id": "2",
              "published": true,
              "uuid": "5f8a1234-5678-90ab-cdef-123456789abc",
              "analysis": "2",
              "distribution": "3",
              "org_id": "1",
              "orgc_id": "1",
              "attribute_count": "15",
              "event_creator_email": "analyst@security.org",
              "tags": ["tlp:amber", "ddos:volumetric", "mitre-attack:T1498"]
            },
            {
              "id": "1002", 
              "info": "Botnet Infrastructure for UDP Amplification",
              "date": "2025-10-06",
              "threat_level_id": "3",
              "published": true,
              "uuid": "5f8a1234-5678-90ab-cdef-987654321def",
              "analysis": "1",
              "distribution": "2",
              "org_id": "2",
              "orgc_id": "2", 
              "attribute_count": "23",
              "event_creator_email": "threat@cybersec.com",
              "tags": ["tlp:white", "ddos:amplification", "botnet:mirai"]
            },
            {
              "id": "1003",
              "info": "Layer 7 HTTP Flood Against E-commerce",
              "date": "2025-10-05",
              "threat_level_id": "2",
              "published": false,
              "uuid": "5f8a1234-5678-90ab-cdef-456789012345",
              "analysis": "0",
              "distribution": "1",
              "org_id": "1",
              "orgc_id": "1",
              "attribute_count": "8",
              "event_creator_email": "soc@company.com",
              "tags": ["tlp:green", "ddos:application-layer", "mitre-attack:T1498.001"]
            }
          ],
          "attributes": [
            {
              "id": "5001",
              "event_id": "1001",
              "type": "ip-src",
              "category": "Network activity",
              "value": "185.220.100.240",
              "comment": "C2 server for DDoS botnet",
              "to_ids": true,
              "uuid": "attr-uuid-001",
              "timestamp": "1696636800",
              "tags": ["ddos:c2", "malicious-infrastructure"]
            },
            {
              "id": "5002",
              "event_id": "1001", 
              "type": "ip-src",
              "category": "Network activity",
              "value": "198.51.100.150",
              "comment": "Amplification reflector",
              "to_ids": true,
              "uuid": "attr-uuid-002",
              "timestamp": "1696636800",
              "tags": ["ddos:amplifier", "ntp-amplification"]
            },
            {
              "id": "5003",
              "event_id": "1002",
              "type": "domain",
              "category": "Network activity", 
              "value": "evil-botnet.example.com",
              "comment": "Botnet command domain",
              "to_ids": true,
              "uuid": "attr-uuid-003",
              "timestamp": "1696550400",
              "tags": ["ddos:domain", "botnet:mirai"]
            }
          ],
          "organizations": [
            {
              "id": "1",
              "name": "Security Operations Center",
              "uuid": "org-uuid-001",
              "description": "Primary threat intelligence team",
              "type": "CSIRT",
              "nationality": "US",
              "local": true
            },
            {
              "id": "2", 
              "name": "CyberSec Research Lab",
              "uuid": "org-uuid-002",
              "description": "External research partnership",
              "type": "Private Sector",
              "nationality": "EU",
              "local": false
            }
          ],
          "tags": [
            {
              "id": "101",
              "name": "tlp:amber",
              "colour": "#FFC000",
              "exportable": true,
              "count": 1
            },
            {
              "id": "102",
              "name": "ddos:volumetric", 
              "colour": "#FF6B6B",
              "exportable": true,
              "count": 1
            },
            {
              "id": "103",
              "name": "mitre-attack:T1498",
              "colour": "#4ECDC4",
              "exportable": true,
              "count": 2
            },
            {
              "id": "104",
              "name": "botnet:mirai",
              "colour": "#45B7D1",
              "exportable": true,
              "count": 2
            }
          ],
          "summary": {
            "totalEvents": 3,
            "totalAttributes": 3,
            "totalOrganizations": 2,
            "totalTags": 4,
            "threatLevels": {
              "high": 2,
              "medium": 1,
              "low": 0,
              "undefined": 0
            },
            "analysisStatus": {
              "initial": 1,
              "ongoing": 1, 
              "completed": 1
            },
            "publishedEvents": 2,
            "unpublishedEvents": 1
          },
          "lastUpdated": "$TIMESTAMP",
          "source": "sample-data-for-demo",
          "note": "This is sample data for proof of concept. Production will use real MISP instance."
        }
        EOF
        
        echo "Generated comprehensive sample MISP data for dashboard demo"
        
    - name: Generate timestamp
      run: |
        echo "TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV
        
    - name: Create data directory if it doesn't exist
      run: |
        mkdir -p webapp/frontend/public/data
        
    - name: Update data timestamp  
      run: |
        echo "{\"lastUpdated\": \"$TIMESTAMP\", \"source\": \"sample-data-demo\", \"dataType\": \"proof-of-concept\", \"note\": \"Sample DDoS threat intelligence data for demonstration\"}" > webapp/frontend/public/data/last-update.json

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: webapp/frontend/package-lock.json

    - name: Install frontend dependencies
      run: |
        cd webapp/frontend
        npm ci

    - name: Build frontend
      run: |
        cd webapp/frontend
        npm run build

    - name: Commit and push updated data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add webapp/frontend/public/data/
        git diff --staged --quiet || git commit -m "Update MISP dashboard data - $TIMESTAMP"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./webapp/frontend/dist
        enable_jekyll: false
        force_orphan: true